config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  
  # sessions routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # users routes
  get '/users/:id' => 'users#show', as: 'user'

  # securities routes
  get '/securities/find' => 'securities#new'
  resources :securities do
    resources :watchlists, only: [:new]
    collection do
      get 'best_performing'
    end
  end

  # watchlists routes
  resources :watchlists do
    resources :securities, only: [:index, :new, :create]
  end
  post '/securities/:id' => 'securities#refresh'

end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
    belongs_to :user
    belongs_to :security
    scope :rolled_up, ->(wl) { where("name = ? AND user_id = ?", wl.name, wl.user_id)}

    def self.roll_up_secs(wl)
        rolled_up(wl).map {|wl| wl.security}
    end

    def self.full_sec_attributes(wl, att)
        roll_up_secs(wl).map {|sec| sec.send(att)}
    end

    def self.total_up(wl, att)
        total = 0
        roll_up_secs(wl).each {|sec| total += sec.send(att)}
        total
    end

    def self.total_change(wl)
        change = total_up(wl, 'change') / total_up(wl, 'previousClose') * 100
        change.to_f.round(3)
    end

end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
    before_action :authenticate_user!

    # future enhancement: refresh watchlist -> watchlist_securities.each update(...)

    def index
        wl = current_user.watchlists.select(:name).distinct
        @watchlists = wl.map {|wlname| Watchlist.find_by(name: wlname.name) }
    end

    def new
        @watchlist = Watchlist.new
        @sec_id = params[:sec_id]
    end

    def create
        @watchlist = Watchlist.find_by(name: watchlist_params[:name], security_id: watchlist_params[:security_id], user_id: current_user.id)
        if @watchlist
            redirect_to security_path(@watchlist.security_id), alert: "Security already associated with Watchlist"
        else
            mod_watchlist = Watchlist.find_by(name: watchlist_params[:name], user_id: current_user.id)
            if mod_watchlist
                @watchlist = Watchlist.create(name: mod_watchlist.name, description: mod_watchlist.description, security_id: watchlist_params[:security_id], user_id: current_user.id)
                redirect_to security_path(@watchlist.security_id), alert: "Security added to Watchlist"
            else
                @watchlist = Watchlist.create(name: watchlist_params[:name], description: watchlist_params[:description], security_id: watchlist_params[:security_id], user_id: current_user.id)
                redirect_to security_path(@watchlist.security_id), alert: "Watchlist created and Security added"
            end
        end
    end

    def edit
        @watchlist = Watchlist.find(params[:id])
    end

    def update
        @watchlist = Watchlist.find(params[:id])
        Watchlist.rolled_up(@watchlist).each do |wl|
            wl.update(watchlist_params)
        end
        redirect_to watchlist_path(@watchlist)
    end

    def show
        @watchlist = Watchlist.find(params[:id])
    end

    def destroy
        Watchlist.find(params[:id]).destroy
        redirect_to security_path(params[:sec_id])
    end

    private
    def watchlist_params
        params.require(:watchlist).permit(:name, :description, :security_id)
    end

    def set_user
        UserInfo.current_user = session[:user]
    end

end

app/views/watchlists/edit.html.erb
<div class='form'><h1>Edit Watchlist</h1><br>
    <%= form_for @watchlist do |f| %>
        <p><%= f.label :name %></p>
        <%= f.text_field :name %>
        <p><%= f.label :description %></p>
        <%= f.text_area :description %>
        <br>
        <%= f.submit class: 'submit-btn' %>
    <% end %>
</div>

app/views/watchlists/index.html.erb
<h1>Watchlists</h1>
<br>

<ol><% @watchlists.each do |wl| %>
    <li><%= link_to wl.name, watchlist_path(wl), class:"table-link" %> - <%= wl.description %>
        <ul>
            <li><%= Watchlist.rolled_up(wl).count %> <%= "security".pluralize(Watchlist.rolled_up(wl).count) %> worth $ <%= Watchlist.total_up(wl, 'latestPrice') %>, a total change of <%= Watchlist.total_change(wl) %>%</li>
        </ul>
    </li><br>
<% end %></ol>

app/views/watchlists/new.html.erb
<div class='form'><h1>Add to Watchlist</h1><br>
    <%= form_for @watchlist do |f| %>
        <%= f.hidden_field :security_id, value: @sec_id %>
        <p><%= f.label "Create a new Watchlist:" %></p>
        <p><%= f.label :name %></p>
        <%= f.text_field :name %>
        <p><%= f.label :description %></p>
        <%= f.text_area :description %><br><br>
        

        <p><%= f.label "Or choose existing Watchlist to add Security:" %></p>
        <% current_user.watchlists.map{|wl| wl.name}.uniq.each do |name| %>
            <p><%= f.radio_button :name, name %><%= f.label :name, name %></p>
        <% end %>
        <br>
        <%= f.submit class: 'submit-btn' %>
    <% end %>
</div>

app/views/watchlists/show.html.erb
<h1><%= @watchlist.name %></h1>
<p><i><%= @watchlist.description %></i></p>
<%= form_tag(edit_watchlist_path(@watchlist), method:'GET', enforce_utf8: false) do %>
    <%= submit_tag "Edit Watchlist", name: nil %>
<% end %>
    
<br><br>
<h2><%= Watchlist.roll_up_secs(@watchlist).count %> <%= "Security".pluralize(Watchlist.roll_up_secs(@watchlist).count) %></h2>
<%= form_tag(watchlist_securities_path(@watchlist), method:'GET', enforce_utf8: false) do %>
    <%= submit_tag "View Securities", name: nil %>
<% end %>

<br>
<h2>Recent Performance:</h2>
<p>Total Watchlist Value: $<%= Watchlist.total_up(@watchlist, "latestPrice") %></p>
<p>Total Change: $<%= "%.2f" % Watchlist.total_up(@watchlist, 'change').to_f %> (<%= Watchlist.total_change(@watchlist) %>%)</p>