config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  
  # sessions routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # users routes
  get '/users/:id' => 'users#show', as: 'user'

  # securities routes
  get '/securities/find' => 'securities#new'
  resources :securities do
    resources :watchlists, only: [:new]
    collection do
      get 'best_performing'
    end
  end

  # watchlists routes
  resources :watchlists do
    resources :securities, only: [:index, :new, :create]
  end
  post '/securities/:id' => 'securities#refresh'

end

app/models/security.rb
class Security < ApplicationRecord
    has_many :watchlists
    has_many :users, through: :watchlists

    validates :symbol, :companyName, presence: true
    before_validation :symbol_upcase
    before_validation :convert_decimals
    
    scope :best_performing, -> { order(changePercent: :desc).limit(5) }

    def self.look_up_security(sec_hash)
        symbol = sec_hash[:symbol].upcase
        company_name = sec_hash[:companyName]
        security_field_ary = Security.new.attributes.keys
        
        if !symbol.blank?
            security = Security.find_by(symbol: symbol)
            if !security
                security = Security.find_by(companyName: company_name)
                if !security
                    begin
                        data = StockQuote::Stock.raw_quote(symbol)["#{symbol}"]["quote"].select {|k,v| security_field_ary.include?(k)}
                        security = Security.new(data)
                    rescue
                        return "No securities match given symbol or company_name. Enter new symbol or company name."
                    end
                end
            end
            if security.valid?
                security.save
                return security
            else
                return "Data returned from source was not a valid Security (must have a Symbol and a Company Name). Go to https://iextrading.com/apps/stocks/#{symbol} to view on IEX Site."
            end
        elsif !company_name.blank?
            security = Security.find_by(companyName: company_name)
            # IEX API doesn't allow searching by company_name - add this in future release
            # if !security
            #     begin
            #           data = StockQuote::Stock.raw_quote(company_name)["#{company_name}"]["quote"]
            #           security = Security.new(data)
            #     rescue
                if !security
                    return "No securities match given symbol or company_name. Enter new symbol or company name."
                end
            # end
            if security.valid?
                security.save
                return security
            else
                return "Data returned from source was not a valid Security (must have a Symbol and a Company Name). Go to https://iextrading.com/apps/stocks/#{symbol} to view on IEX Site."
            end
        else
            return "Must enter a company symbol or name to search."
        end
    end

    def refresh_security(sec_hash)
        self.symbol = sec_hash["symbol"]
        self.companyName = sec_hash["companyName"]
        self.primaryExchange = sec_hash["primaryExchange"]
        self.calculationPrice = sec_hash["calculationPrice"]
        self.open = sec_hash["open"].to_f
        self.close = sec_hash["close"]
        self.high = sec_hash["high"]
        self.low = sec_hash["low"]
        self.latestPrice = sec_hash["latestPrice"]
        self.latestSource = sec_hash["latestSource"]
        self.latestUpdate = sec_hash["latestUpdate"]
        self.latestVolume = sec_hash["latestVolume"]
        self.previousClose = sec_hash["previousClose"]
        self.change = sec_hash["change"]
        self.changePercent = sec_hash["changePercent"]
        self.market_cap = sec_hash["market_cap"]
        self.peRatio = sec_hash["peRatio"]
        self.week52High = sec_hash["week52High"]
        self.week52Low = sec_hash["week52Low"]
        self.ytdChange = sec_hash["ytdChange"]
    end

    def symbol_upcase
        self.symbol.upcase
    end

    def convert_decimals
        self.open = "%.2f" % self.open.to_f
        self.close = "%.2f" % self.close.to_f
        self.high = "%.2f" % self.high.to_f
        self.low = "%.2f" % self.low.to_f
        self.latestPrice = "%.2f" % self.latestPrice.to_f
        self.previousClose = "%.2f" % self.previousClose.to_f
        self.change = "%.2f" % self.change.to_f
        self.changePercent = self.changePercent.to_f.round(3)
        self.week52High = "%.2f" % self.week52High.to_f
        self.week52Low = "%.2f" % self.week52Low.to_f
        self.ytdChange = "%.2f" % self.ytdChange.to_f
    end

end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def index
        if params[:watchlist_id]
            @watchlist = Watchlist.find(params[:watchlist_id])
            @securities = Watchlist.rolled_up(@watchlist).map {|wl| wl.security}
        else
            @securities = Security.all.limit(10)
        end
    end

    def best_performing
        @securities = Security.best_performing
    end

    def new
        @security = Security.new
    end

    def create
        @security = Security.look_up_security(security_params)
        if !@security.class.eql?(Security)
            redirect_to new_security_path, alert: @security
        else
            redirect_to security_path(@security)
        end
    end

    def update
        @security = Security.find(params[:id])
    end

    def refresh
        @security = Security.find(params[:id])
        begin 
            data = StockQuote::Stock.raw_quote(@security.symbol)["#{@security.symbol}"]["quote"]
            @security.refresh_security(data)
            if @security.valid?
                @security.save
                redirect_to security_path(@security), message: "Security data has been updated successfully"
            else
                flash[:message] = "Refresh Unsuccessful: Security data located, but not valid."
                render 'securities/show'
            end
        rescue RuntimeError => e
            flash[:message] = "Security Symbol not found - could not update"
            redirect_to security_path(@security)
        end
    end

    def destroy
        @security = Security.find(params[:id])
        @security.watchlists.where("user_id = ?", current_user.id).destroy_all
        redirect_to securities_path, alert: "Requested Security has been removed from all watchlists"
    end

    def show
        @security = Security.find(params[:id])
    end

    private
    def security_params
        params.require(:security).permit(:symbol, :companyName, :primaryExchange, :calculationPrice, :open, :close, :high, :low, :latestPrice, :latestSource, :latestUpdate, :latestVolume, :previousClose, :change, :changePercent, :marketCap, :peRatio, :week52High, :week52Low, :ytdChange, watchlist_ids: [], watchlists_attributes: [:name, :description])
    end
end

app/views/securities/_display_table.html.erb
<table id="sec-index-table">
    <tr>
        <th>Symbol</th>
        <th>Company</th>
        <th>Latest Volume</th>
        <th>Latest Price</th>
        <th>Price Change</th>
        <th>Percent Change</th>
        <th>Change YTD</th>
        <% if template == 'user' %>
            <th>Watchlists</th>
        <% else %>
            <th>In Portfolio</th>
        <% end %>
        <th>Last Update</th>
    <tr>
    <% secs.each do |sec| %>
        <tr>
            <td><%= link_to sec.symbol, security_path(sec), class:"table-link" %></td>
            <td><%= sec.companyName %></td>
            <td><%= sec.latestVolume %></td>
            <td>$<%= sec.latestPrice%></td>
            <td>$<%= sec.change%></td>
            <td><%= sec.changePercent %>%</td>
            <td>$<%= sec.ytdChange%></td>
            <% if template == 'user' %>
                <td><%= sec.watchlists.count %></td>
            <% else %>
                <td><%= sec.watchlists.count > 0 ? "Yes" : "No" %></td>
            <% end %>
            <td><%= sec.updated_at.strftime('%b %e, %Y at %l:%M%P') %></td>
        </tr>
    <% end %>
</table>
<br>

<%= form_tag(new_security_path, method: 'GET', enforce_utf8: false) do %>
    <%= submit_tag "Lookup Security", name: nil %>
<% end %>

app/views/securities/best_performing.html.erb
<h1>Best Performing Securities</h1>
<ol><% @securities.each do |sec| %>
    <li> <%= sec.symbol %>
        <ul>
            <li>Change Percent: <%= sec.changePercent %></li>
            <li>Change: <%= sec.change %></li>
            <li>Latest Price: <%= sec.latestPrice %></li>
        </ul>
    </li><br>
<% end %></ol>

app/views/securities/index.html.erb
<% if @watchlist %>
    <h1><%= @watchlist.name %> Securities</h1>
<% else %>
    <h1>Recently Searched Securities</h1>
<% end %>

<%= render partial: 'display_table', locals: {secs: @securities, template: 'index'} %>

app/views/securities/new.html.erb
<%= alert %>

<h1>Securities Lookup</h1>

<%= form_for @security do |f| %>
    <p><%= f.label :symbol %></p>
    <%= f.text_field :symbol %>
    <p><%= f.label :companyName, "Company Name" %></p>
    <%= f.text_field :companyName %><br><br>
    <%= f.submit value: "Lookup Security", class: 'submit-btn' %>
<% end %>
<br>
<h5><i>Only one field required, if both are entered priority will go to symbol.</i></h5>

app/views/securities/othernew.html.erb
<div class='form'><h1>Add to Watchlists</h1><br>
<%= form_for @security do |f| %>
    <% flash.keep(:passed_sec) %>
    <p><%= f.label "Select Watchlist(s) for #{@security.symbol}:" %></p>
    <%= f.collection_check_boxes(:watchlist_names, current_user.watchlists.names.uniq, :name, :name, {checked: @security.watchlist_names.map(&:to_param)}) %>
    <br><br>
    <p><%= f.label :new_watchlist, "Or start a new Watchlist for #{@security.symbol}:" %></p>
    <%= f.fields_for :watchlists, @security.watchlists.build do |wl| %>
        <p><%= wl.label :name %></p>
        <%= wl.text_field :name %>
        <p><%= wl.label :description %></p>
        <%= wl.text_area :description %>
    <% end %>
    <br><br>
    <%= f.submit "Add to Selected", class: 'submit-btn' %>
<% end %>
</div>

app/views/securities/show.html.erb
<%= alert %>

<h1><%= @security.symbol %> - <%= @security.companyName %></h1>

<br><br><h2><u>Summary</u></h2><br>
<ul>
    <li>Latest Price: $<%= @security.latestPrice %></li>
    <li>Change: $<%= @security.change %> (<%= @security.changePercent %>%)</li>
    <li>YTD Change: $<%= @security.ytdChange %></li>
    <li>Latest Volume: <%= @security.latestVolume %></li>
    <li>Latest Update: <%= @security.latestUpdate %></li>
</ul>

<br>
<div class="button_list">
<h2><u>Actions</u></h2>
    <% if current_user.securities.include?(@security) %><br>
        <h4>Associated Watchlists:</h4><br>
        <ul><% current_user.watchlists.select{|wl| wl.security_id.eql?(@security.id)}.each do |watchlist| %>
            <li><%= form_tag("/watchlists/#{watchlist.id}", method: 'DELETE') do %>
                <%= hidden_field_tag :sec_id, @security.id %>
                <strong><%= link_to watchlist.name, watchlist_path(watchlist) %>:</strong>&nbsp;&nbsp; <i><%= watchlist.description %></i>&nbsp;&nbsp;-&nbsp; 
                <%= submit_tag "Remove from Watchlist" %>
            <% end %></li>
        <% end %></ul><br>
        <%= form_tag(new_security_watchlist_path(@security), method: 'GET', enforce_utf8: false) do %>
            <%= hidden_field_tag :sec_id, @security.id %>
            <%= submit_tag "Add to Watchlist", name: nil %>
        <% end %>
        <%= form_with(URL: "/securities/#{@security.id}", method: 'DELETE') do %>
            <%= submit_tag "Remove from Portfolio", class: "submit-btn" %>
        <% end %><br>
    <% else %>
        <%= form_tag(new_security_watchlist_path(@security), method: 'GET', enforce_utf8: false) do %>
            <%= hidden_field_tag :sec_id, @security.id %>
            <%= submit_tag "Add to Portfolio", name: nil %>
        <% end %>
    <% end %>
</div>

<%= render partial: 'registrations/errors', locals: {record:@security} %>
<%= flash[:message] %>
<br>
<h2><u>Full Security Data</u></h2>
<span style="position:relative;bottom:22px;left:155px"><%= form_for(@security, method: 'POST') do |f| %>
    <%= f.submit "Refresh Data", class: 'submit-btn' %>
<% end %></span>

<ul><% @security.attributes.each do |att, val| %>
    <li><strong><%= att %>:</strong> <%= val %></li>
<% end %></ul>