config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  
  # sessions routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # users routes
  get '/users/:id' => 'users#show', as: 'user'

  # securities routes
  get '/securities/find' => 'securities#new'
  resources :securities do
    resources :watchlists, only: [:new]
    collection do
      get 'best_performing'
    end
  end

  # watchlists routes
  resources :watchlists do
    resources :securities, only: [:index, :new, :create]
  end
  post '/securities/:id' => 'securities#refresh'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    include ApplicationHelper

    def welcome
        if user_signed_in?
            render 'welcome'
        else
            render 'login_links'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # def require_login
    #     unless logged_in?
    #         redirect_to root_path, alert: "Must be signed in to access the requested page"
    #     end
    # end
    
end

app/views/application/login_links.html.erb
<h1 style="font-size:3em;">Welcome to StockStack!</h1><br><br>

<%= alert %><br>

<div style="text-align:left;">
    <h2><%= link_to "Sign In", new_user_session_path, class: 'table-link' %> to view your content</h2><br> 
    <h2><%= link_to "Sign Up", new_user_registration_path, class: 'table-link' %> if you are new to the site</h2>
</div>
<br><br><h2>or</h2><br>

<div style="width:23%;text-align:center">
    <div style="height:15px">
        <%= link_to image_tag('/assets/facebook.png'), user_facebook_omniauth_authorize_path, class: 'oauth_pic' %>
    </div>
    <div>
        <h3><%= link_to "Log In with Facebook to get started.", user_facebook_omniauth_authorize_path, class: 'table-link' %></h3>
    </div>
</div>

app/views/application/welcome.html.erb
<div class="ipo-window">
    <%= link_to image_tag('/assets/IPO.jpg'), '#' %>
</div>

<div class="indicator-chart">
    <%= link_to image_tag('/assets/macd-indicator.png'), watchlists_path %>
</div>

<div class="hotlist">
    <%= link_to image_tag('/assets/Popular.jpg'), securities_path %>
</div>

<div class="headlines-box">
    <%= link_to image_tag('/assets/headline.jpg'), '#' %>
</div>

<div class="best-performing-box">
    <%= link_to image_tag('/assets/best-performing.jpg'), best_performing_securities_path %>
</div>