config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  
  # sessions routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # users routes
  get '/users/:id' => 'users#show', as: 'user'

  # securities routes
  get '/securities/find' => 'securities#new'
  resources :securities do
    resources :watchlists, only: [:new]
    collection do
      get 'best_performing'
    end
  end

  # watchlists routes
  resources :watchlists do
    resources :securities, only: [:index, :new, :create]
  end
  post '/securities/:id' => 'securities#refresh'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockStack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="flex-container">
    <body>
      <header>
        <div class="site-menu">
          <%= link_to "Home", root_path %>
          <%= link_to "My Watchlists", watchlists_path %>
          <%= link_to "IPO Center (coming soon)", '#' %>
          <%= link_to "Top Securities", securities_path %>
        </div>
        <div class="site-title">
          <span id="site-title-img"><img src="/assets/StockStack_line2.png" alt="Welcome to StockStack!"></span>
        </div>
        <div class="profile">
          <% if user_signed_in? %>
            <% if current_user.image %>
              <%= link_to image_tag(current_user.image), user_path(current_user) %>
            <% else %>
              <%= link_to "Profile Actions", user_path(current_user), style: '' %>
            <% end %>
            <h3 style="position:relative;bottom:9%"><%= current_user.name %></h3>
          <% end %>
        </div>
        <div class="marquis">
          <% if user_signed_in? %>
            <p><%= current_user.securities.collect {|s| "#{s.symbol}: #{s.changePercent.to_f.round(3)}"}.uniq.join(" || ") %></p>
          <% end %>
        </div>
      </header>

      <main>
        <%= yield %>
      </main>
      
      <footer>
        <div class="footer-section first">
          <p>There would normally be some cool links here</p>
        </div>
        <div class="footer-section">
          <p>But I didn't have any content to add</p>
        </div>
        <div class="footer-section last">
          <p>Plus I just wanted to get this finished up!</p>
        </div>
      </footer>
    </body>
  </div>
</html>